### PR TITLE
add pulp build system

### PR DESCRIPTION
**Pull request by brainrake**

### CODE REVIEW

**Comment by joneshf** [comment]
Cool, Thanks! I'll give it a go when I get a minute.

**Comment by joneshf** [comment]
Sorry for the delay. I gave this a try, and this was the output:

```
* ERROR: No bower.json found in current or parent directories. Are you in a PureScript project?
[Finished in 0.4s with exit code 1]
[cmd: ['pulp', 'run']]
[dir: /home/joneshf/.config/sublime-text-3/Projects]
[path: /home/joneshf/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/plan9/bin:/usr/lib/smlnj/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/bin:/usr/local/bin]
```

Do I need to set something up?

EDIT: `pulp` works from the command line.

**Comment by brainrake** [comment]
Use it like this: 
- create a directory, and run `pulp init` in it
- open the dir with Sublime's `File -> Open Folder`
- select the `pulp` build system (or Sublime should detect it if you have a `.purs` file open)
- press `C-b` (Build) to `pulp test` and `C-S-b` (Run) to `pulp run` (I guess that's `Cmd-b` and `Cmd-Shift-b` on mac)

I think you didn't have a Folder or Project open in sublime, but this build system works with `${project_path}` rather than `${file_path}` because you want to run pulp from the project's root, not from eg. `src/`, so it needs a project or dir open.

This works well for node projects. `pulp browserify` could be another build system, but there's no default output file.

**Comment by brainrake** [comment]
In your output, on the line

```
[dir: /home/joneshf/.config/sublime-text-3/Projects]
```

You can see that `pulp` was run in the wrong directory

**Comment by joneshf** [comment]
Oh, I see. I have  project with all my ps stuff, so that's where it was getting that dir. `project_path` doesn't work, but if I change it to `file_path` or just delete the field all together it seems to work.

I think using `project_path` gives the wrong behavior. If I open just one directory in sublime, it wont build unless I'm on a `purs` file anyway. `pulp` searches for `bower.json` and `src` directories and stuff automatically, so using `project_path` doesn't really work if your project file isn't in the same directory as the directory you're wanting to build. And I don't want to force people to change where they store their project files just to use `pulp`.

Thoughts?

**Comment by brainrake** [comment]
You're right, if the project file is in a different directory, `file_path` is a better option, since `pulp` can find the project root by itself.

**Comment by brainrake** [comment]
`file_regex` could use some improvement as well, it doesn't catch multi-line error output from `psc`.

**Comment by joneshf** [comment]
Okay. I'm not entirely sure how that's supposed to work. I rarely use the build command with sublime, so if you think it's good as is I'll merge, or if you want to wait that's fine as well.

**Comment by brainrake** [comment]
Build errors are reported relative to the project root (as determined by `pulp`) so the path matched by `file_regex` will be incorrect, since the currently open file's path is the working directory. I've removed `file_regex` from the build file until I can think of a solution. The rest should be ok to merge.

**Comment by joneshf** [comment]
Thanks!

**Pull request merged**
